[package]
name = "nixwriter"
version = "3.0.0"
authors = ["adnan338"]
edition = "2018"

[dependencies.gtk]
version = "0.9.0"
features = ["v3_22"]

[dependencies]
zbus = "1.1.1"
zvariant = "2.1.0"
gio = "0.9.0"
glib = "0.10.1"
libc = "0.2.74"